$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1451028437099.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bb5904374084644b3c530becd57773c",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"726dfc32881d4467b78ac131507d062d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":0},
            "size":{
              "width":780,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"290ad099bac0488f864f6f087efac449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":0},
                "size":{
                  "width":780,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.JPG"}},
{
          "id":"a7b8ada040f44689b131e36017c1cf5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Adobe 宋体 Std L Oblique', 'Adobe 宋体 Std'",
            "fontSize":"48px",
            "fontWeight":"300",
            "fontStyle":"oblique",
            "fill":{
              "fillType":"solid",
              "color":0xFF38B5E3},
            "location":{
              "x":380,
              "y":150},
            "size":{
              "width":480,
              "height":60},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"27"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c49d7876070475a947c6b33b609dbd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 宋体 Std L Oblique', 'Adobe 宋体 Std'",
                "fontSize":"48px",
                "fontWeight":"300",
                "fontStyle":"oblique",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF38B5E3},
                "location":{
                  "x":380,
                  "y":150},
                "size":{
                  "width":480,
                  "height":60},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"27"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"d5dc3a2dbe2940b39707c90af92858be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":150},
            "size":{
              "width":100,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a320b093741b4bf0a484ddc59a438221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":150},
                "size":{
                  "width":100,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u4.JPG"}},
{
          "id":"ab1d773ee46a4ff4b2532ff9db45ae99",
          "label":"userName",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":325},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"01a0bf88563a40739f91e5bb3295b904",
          "label":"pwd",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":370},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e51816a886364144aa0e9b1fff22f100",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Adobe 黑体 Std R Bold', 'Adobe 黑体 Std'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF35B6F0},
            "location":{
              "x":640,
              "y":429},
            "size":{
              "width":135,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6377a120c82442c3b312d0f5580d7cfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Adobe 黑体 Std R Bold', 'Adobe 黑体 Std'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF35B6F0},
                "location":{
                  "x":640,
                  "y":429},
                "size":{
                  "width":135,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u8.png"}},
{
          "id":"555f54e5abbb48fdaf2eee250e70a712",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":503},
            "size":{
              "width":470,
              "height":70},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"24"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310b2b158c974238ae4c74ad5f3fb3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":503},
                "size":{
                  "width":470,
                  "height":70},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"24"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u10.png"}},
{
          "id":"a337b3de1a3c460ea6ca6d97b16aafed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF38B5E3},
            "location":{
              "x":770,
              "y":150},
            "size":{
              "width":90,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5df464e66d4d338ee64216510c5c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF38B5E3},
                "location":{
                  "x":770,
                  "y":150},
                "size":{
                  "width":90,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u12.png"}},
{
          "id":"3d4d53c1d6444837afd6db75bfd2b566",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":402},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9399762a088049e7b20b578d7faea9a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":402},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3773fb1f625497bb205a6bf4c4d1818",
          "label":"codeimg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":399},
            "size":{
              "width":84,
              "height":25}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b9b6efeab755400eb5b01987b3bf67bd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8e0ec03ec5f44960b14534935f52658e",
                  "label":"",
                  "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta cursiva', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "fontStyle":"italic",
                    "size":{
                      "width":110,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4baa43ec1384173a09818ff35a33e52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta cursiva', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "fontStyle":"italic",
                        "size":{
                          "width":110,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆/u17.png"}}]},
{
              "id":"c50b410cae824814b2a26503958f0e97",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5a872c1abfc74e998e7dd54011becdd0",
                  "label":"",
                  "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta cursiva', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "fontStyle":"italic",
                    "size":{
                      "width":110,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93b7bfc3b2fa4ceebe044a53b2e22aac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta cursiva', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "fontStyle":"italic",
                        "size":{
                          "width":110,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆/u17.png"}}]},
{
              "id":"81548daa48c444bbbc6ea8f7621eb049",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5eac9f6d52b84d2494148a35ff43133d",
                  "label":"",
                  "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta cursiva', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "fontStyle":"italic",
                    "size":{
                      "width":110,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"028388a1f322470e9c84c9a6483626b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3773fb1f625497bb205a6bf4c4d1818",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta cursiva', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "fontStyle":"italic",
                        "size":{
                          "width":110,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆/u17.png"}}]}]},
{
          "id":"f4612374d10a422984c39d703b55562c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":639,
              "y":399},
            "size":{
              "width":63,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5bb991d22a5040c592366b51692dd45f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":787,
              "y":397},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a9eb93c343a4abbb26494681c82c511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":787,
                  "y":397},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 codeimg to 下一步 wrap",
                      "panelsToStates":[{
                          "panelPath":["b3773fb1f625497bb205a6bf4c4d1818"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "726dfc32881d4467b78ac131507d062d":{
      "scriptId":"u0"},
    "290ad099bac0488f864f6f087efac449":{
      "scriptId":"u1"},
    "a7b8ada040f44689b131e36017c1cf5e":{
      "scriptId":"u2"},
    "8c49d7876070475a947c6b33b609dbd3":{
      "scriptId":"u3"},
    "d5dc3a2dbe2940b39707c90af92858be":{
      "scriptId":"u4"},
    "a320b093741b4bf0a484ddc59a438221":{
      "scriptId":"u5"},
    "ab1d773ee46a4ff4b2532ff9db45ae99":{
      "scriptId":"u6"},
    "01a0bf88563a40739f91e5bb3295b904":{
      "scriptId":"u7"},
    "e51816a886364144aa0e9b1fff22f100":{
      "scriptId":"u8"},
    "6377a120c82442c3b312d0f5580d7cfc":{
      "scriptId":"u9"},
    "555f54e5abbb48fdaf2eee250e70a712":{
      "scriptId":"u10"},
    "310b2b158c974238ae4c74ad5f3fb3d3":{
      "scriptId":"u11"},
    "a337b3de1a3c460ea6ca6d97b16aafed":{
      "scriptId":"u12"},
    "2f5df464e66d4d338ee64216510c5c01":{
      "scriptId":"u13"},
    "3d4d53c1d6444837afd6db75bfd2b566":{
      "scriptId":"u14"},
    "9399762a088049e7b20b578d7faea9a3":{
      "scriptId":"u15"},
    "b3773fb1f625497bb205a6bf4c4d1818":{
      "scriptId":"u16"},
    "8e0ec03ec5f44960b14534935f52658e":{
      "scriptId":"u17"},
    "b4baa43ec1384173a09818ff35a33e52":{
      "scriptId":"u18"},
    "5a872c1abfc74e998e7dd54011becdd0":{
      "scriptId":"u19"},
    "93b7bfc3b2fa4ceebe044a53b2e22aac":{
      "scriptId":"u20"},
    "5eac9f6d52b84d2494148a35ff43133d":{
      "scriptId":"u21"},
    "028388a1f322470e9c84c9a6483626b0":{
      "scriptId":"u22"},
    "f4612374d10a422984c39d703b55562c":{
      "scriptId":"u23"},
    "5bb991d22a5040c592366b51692dd45f":{
      "scriptId":"u24"},
    "2a9eb93c343a4abbb26494681c82c511":{
      "scriptId":"u25"}}});